site_name: Tech Writing Portfolio
site_description: Documentation samples by Chafyn H
site_url: https://ChafynH.github.io/tech-writing-portfolio/
repo_url: https://github.com/ChafynH/tech-writing-portfolio
edit_uri: edit/main/docs/
repo_name: ChafynH/tech-writing-portfolio

theme:
  name: material
  language: en
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.top          # keeps the nav visible when scrolling
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences

nav:
  - Home: index.md
  - About: about.md
  - Guides:
      - Installing VLC Media Player: guides/vlc-installation.md
  - Trados — Getting Started:
      - Overview: trados-getting-started/index.md
      - Quick start: trados-getting-started/quick-start.md
      - Access help: trados-getting-started/help-guide.md
      - Create a project: trados-getting-started/how-to-create-project.md
      - Troubleshooting: trados-getting-started/troubleshooting.md
      - Keyboard shortcuts: trados-getting-started/keyboard-shortcuts.md
  - DeepL — Getting Started:
      - Overview: deepl-getting-started/index.md
      - Quick start: deepl-getting-started/quick-start.md
      - Use glossaries: deepl-getting-started/how-to-use-glossaries.md
      - Troubleshooting: deepl-getting-started/troubleshooting.md
      - Glossary limits: deepl-getting-started/glossary-limits.md
  - Style guide: style-guide.md
  - Changelog: changelog.md

docs_dir: docs

plugins:
  - search
