site_name: Tech Writing Portfolio
site_description: Documentation samples by Chafyn H
site_url: https://ChafynH.github.io/tech-writing-portfolio/
repo_url: https://github.com/ChafynH/tech-writing-portfolio
edit_uri: edit/main/docs/
repo_name: ChafynH/tech-writing-portfolio

theme:
  name: material
  language: en
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details

nav:
  - Home: index.md
  - About: about.md

  - Guides:
      - Overview: guides/index.md
      - Installing VLC Media Player: guides/vlc-installation.md

      - DeepL — Getting Started:
          - Overview: guides/deepl-getting-started/index.md
          - Quick start: guides/deepl-getting-started/quick-start.md
          - Use glossaries: guides/deepl-getting-started/how-to-use-glossaries.md
          - Troubleshooting: guides/deepl-getting-started/troubleshooting.md
          - Glossary limits: guides/deepl-getting-started/glossary-limits.md

      - DeepL — Glossaries: guides/deepl-glossaries/index.md

      - Trados — Getting Started:
          - Overview: guides/trados-getting-started/index.md
          - Quick start: guides/trados-getting-started/quick-start.md
          - Access help: guides/trados-getting-started/help-guide.md
          - Create a project: guides/trados-getting-started/how-to-create-project.md
          - Troubleshooting: guides/trados-getting-started/troubleshooting.md
          - Keyboard shortcuts: guides/trados-getting-started/keyboard-shortcuts.md

  - Visual Samples: visuals/index.md

  - API Documentation:
      - Overview: guides/api-documentation/index.md
      - OpenWeather API — Getting Started: guides/api-documentation/openweather-api.md
      - OpenWeather API — 5-Day Forecast: guides/api-documentation/forecast-api.md

  - Localization:
      - Overview: localization/index.md
      - VLC Installation (German): localization/vlc-installation-de.md

  - Samples:
      - Rewrite Showcase: samples/before-after.md
      - Writing Exercises: samples/writing-samples.md
      - Visual Sample: samples/visual-sample.md

  - Style guide: style-guide.md
  - Changelog: changelog.md

docs_dir: docs

plugins:
  - search
